pipeline {
    agent { label 'Node_01' }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub_credentials')
    }
    options {
        buildDiscarder(logRotator(numToKeepStr:'5'))
    }
    stages {
        stage('Clone repository') {
            steps {
                git url: 'https://github.com/Julie717/simple-app', branch: 'master'
            }
        }
        stage('Validate Dockerfile'){
            steps {
                sh """
                docker pull hadolint/hadolint:latest-alpine
                docker run --rm -i hadolint/hadolint < Dockerfile
                """
            }
        }
        stage('Build image') {
            steps {
                sh "docker build -t hello-app ."
            }
        }
        stage('Test image') {
            steps {
                sh """
                docker run -d -p 80:80 --name hello-app hello-app
                docker exec -it hello-app sh
                """
            }
        }
        stage('Login to Docker Hub') {
            steps {
                sh """
	            echo $DOCKERHUB_CREDENTIALS_PSW | sudo docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                echo 'Login Completed'
                """
            }
        }
        stage('Push Image to Docker Hub') {
            steps {
                sh """
	            sudo docker push ybuyalskaya/simple-app:$BUILD_NUMBER
	            echo 'Push Image Completed'
	            """
	        }
        }
    }
}