name: Test

on:
  push:
    branches:
      - master

jobs:
  run:
    name: Test simple-app image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
      pages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run simple-app
        run: |
          docker pull ybuyalskaya/simple-app:master
          docker run -d -p 8080:8080 --name simple-app ybuyalskaya/simple-app:master
          sleep 30s

      - name: Install curl
        run: sudo apt install curl

      - name: Test app
        run: |
          RESULT=`curl http://localhost:8080/hello`
          echo $RESULT
          if [ "$RESULT" == "Hello, World!" ]
          then 
            echo "SUCCESS"
          else 
            echo "FAILURE"
            exit 1
          fi

      - name: Check rootless mode
        run: |
          RESULT=`docker exec simple-app whoami`
          echo $RESULT
          if [ "$RESULT" == "user" ]
          then 
            echo "SUCCESS"
          else 
            echo "FAILURE"
            exit 1
          fi          
